pre_keywords = []

post_keywords = []

line_keywords = ['iS registered', 'is registeres', 'is registered', '0 roguterod', 'is registeced', 'ts registered', 'SPONSOR:', "1's registered", '1s registered', 'regntered with the Nation', 'isregistered']

special_keywords  = ['sponsored by', 'CPE Sponsor Name', "Program Sponsor's Name and Address", "Sponsor:", 'Name of Provider:', 'Certified College Financial Consultant -']

sponsor_list = ["AICPA", "Deloitte", "Becker Professional Education", "Intuit", "intuit", "Optiv Security", "FICPA", "KPMG", "EY", "CPA Academy", "Becker", "Beene Garter LLP", "Checkpoint Learning", "PricewaterhouseCoopers LLP", "PWC", "Deloitte LLP", "MACPA", "CPAAcademy.org", "CPAwebengage, Inc.", "Wolters Kluwer", "Grant Thornton LLP", "The Institute of Internal Auditors", "Ernst & Young LLP", "Learning.net", "KPMG LLP", "SC&H Group", "Association of International Certified Professional Accountants", "Thomson Reuters", "RSM", "HoganTaylor LLP", "Western CPE", "MICPA", "Practising Law Institute", "TSCPA", "Plain-English Accounting", "Surgent McCoy CPE, LLC", "Ernst & Young", "Surgent", "OSCPA", "VSCPA", "PricewaterhouseCoopers", "RSM US LLP", "AuditSense", "Becker CPE", "Workiva", "DTTL", "BKD, LLP", "KPMG Executive Education", "Foundation for Accounting Education", "PLI", "ACFE", "Association of Certified Fraud Examiners", "Grant Thornton", "Learnlive Technologies", 'Robert Half', 'The Madray Group', 'The Madray Group, Inc.', 'CPE Solutions, LLC', 'Cliftor LarsonAller LLP', 'SourceMedia Inc.', 'SourceMedia Inc', 'Proformative', 'Perry Glen Moore', 'CPA Crossings', 'CPE DepotInc', 'Financial Accounting Foundation', 'FASB', 'Tennessee Valley Authority', 'Accountants Education Group', 'The CalCPA Education Foundation', 'Sisterson & Co. LLP', 'Sisterson & Co', 'PricewaterhouseCoopersLLP', 'COLBGATE-FALMOLIVE', 'COLBATE-FALAIOLIVIEE', 'CPAacademy.org', 'CCH Incorporated', 'Westerr CPE']

extra_list= ["ASSOCIATION OF CERTIFIED FRAUD EXAMINERS", 'Plaio-English Accounting', 'pliedu', 'the Institute of Internal Auditors', 'WAthe Institute of Internal Auditors', 'Institute of Internal Auditors', 'THOMSON REUTERS', 'The Virginia Society of CPAs', 'Wes:ern CPE', 'Plain-English Acooanting', 'Plain-English Accoanting', 'schoolefbookkeeping', 'The ASCPA CPE', 'Armanino LLP', "Accounting & Financial Women's Alliance", "Corporate Finance", "Management Concepts", 'Adaptive Insights', 'DCB Holding Ltd', 'Plam-English Accounting', 'AudioSolutionZ', 'Dixon Hughes Goodman LLP', 'STEIN SPERLING', 'Frazier & Deeter, LLC', 'Tate & Tryon', 'HogantTaylor', 'HoganTaylor', 'RS M', 'Western CPE', 'Western CPEs']

